import type { Metadata } from "next";
import "@/shared/assets/styles/globals.sass";
import Footer from "@/widgets/footer";
import Header from "@/widgets/header";
import SideBar from "@/widgets/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SideBar />
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
